# Generated by Django 4.2.4 on 2023-09-19 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('station', '0002_facility_order_trip_ticket_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='facility',
            options={'verbose_name_plural': 'facilities'},
        ),
        migrations.AddField(
            model_name='bus',
            name='facilities',
            field=models.ManyToManyField(related_name='buses', to='station.facility'),
        ),
    ]
