# Generated by Django 4.2.4 on 2023-09-25 17:27

from django.db import migrations, models
import station.models


class Migration(migrations.Migration):

    dependencies = [
        ('station', '0005_alter_ticket_trip'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ticket',
            options={'ordering': ('seat',)},
        ),
        migrations.AddField(
            model_name='bus',
            name='image',
            field=models.ImageField(null=True, upload_to=station.models.bus_image_file_path),
        ),
    ]
